
export const white = "#ffff"
export const oysterPink = "#edd0ce"
export const pinkFraud = "#FFC0CB"
export const cottonCandy = "#ffb7ce"
export const copperRust = "#80444c"
export const darkPurple = "#6b52ae"
export const grey = "#333"
export const black = "#000"
export const green = "#85bb65"